#pragma once

#define PROFILE PROFILE_SONOFF_DUAL_POW_R3

#define PROFILE_ESP8266_DEV_KIT 0
#define PROFILE_SONOFF_DUAL_POW_R3 1

#if (PROFILE == PROFILE_ESP8266_DEV_KIT)
    #define PROFILE_DEFAULT_PIN_KEY_UP 2
    #define PROFILE_DEFAULT_PIN_KEY_DOWN 14
    #define PROFILE_DEFAULT_PIN_RELAY_UP 5
    #define PROFILE_DEFAULT_PIN_RELAY_DOWN 4
    #define PROFILE_DEFAULT_KEY_ACTIVE_HIGH false
    #define PROFILE_DEFAULT_KEY_PULL_ACTIVE true
    #define PROFILE_DEFAULT_RELAY_ACTIVE_HIGH false

    #define PROFILE_DEFAULT_PIN_KEY_RESET 0
    #define PROFILE_DEFAULT_PIN_KEY_RESET_ACTIVE_HIGH false
#endif

#if (PROFILE == PROFILE_SONOFF_DUAL_POW_R3)
    #define PROFILE_DEFAULT_PIN_KEY_UP 32
    #define PROFILE_DEFAULT_PIN_KEY_DOWN 33
    #define PROFILE_DEFAULT_PIN_RELAY_UP 27
    #define PROFILE_DEFAULT_PIN_RELAY_DOWN 14
    #define PROFILE_DEFAULT_KEY_ACTIVE_HIGH false
    #define PROFILE_DEFAULT_KEY_PULL_ACTIVE true
    #define PROFILE_DEFAULT_RELAY_ACTIVE_HIGH true

    #define PROFILE_DEFAULT_PIN_KEY_RESET 0
    #define PROFILE_DEFAULT_PIN_KEY_RESET_ACTIVE_HIGH false
#endif